[versions]
kotlin-stdlib = "1.5.0"

core = "1.7.0"
appcompat = "1.4.1"
material = "1.5.0"
constraintlayout = "2.1.3"

navigation = "2.4.2"

junit = "4.13.2"
ext-junit = "1.1.5"
espresso = "3.4.0"

mockito = "3.4.0"

lifecycle = "2.5.1"

coroutine = "1.4.1"
coroutine-test = "1.4.3"

room = "2.4.2"
room-test = "2.2.3"

hilt = "2.40"

[libraries]
kotlin-stdlib = {module = "org.jetbrains.kotlin:kotlin-stdlib",version.ref = "kotlin-stdlib"}
core-ktx = {module = "androidx.core:core-ktx",version.ref ="core"}
appcompat = {module = "androidx.appcompat:appcompat",version.ref = "appcompat"}
material = {module = "com.google.android.material:material",version.ref = "material"}
constraintlayout = {module = "androidx.constraintlayout:constraintlayout",version.ref = "constraintlayout"}

navigation-fragment = {module = "androidx.navigation:navigation-fragment-ktx",version.ref = "navigation"}
navigation-ui = {module = "androidx.navigation:navigation-ui-ktx",version.ref ="navigation"}

junit-junit = {module = "junit:junit",version.ref="junit"}

ext-junit = {module = "androidx.test.ext:junit",version.ref ="ext-junit"}
espresso-core = {module ="androidx.test.espresso:espresso-core",version.ref = "espresso"}

mockito-inline = {module = "org.mockito:mockito-inline",version.ref ="mockito"}

lifecycle-viewmodel = {module = "androidx.lifecycle:lifecycle-viewmodel-ktx",version.ref = "lifecycle"}
lifecycle-runtime = {module ="androidx.lifecycle:lifecycle-runtime-ktx",version.ref = "lifecycle"}

coroutine-core = {module ="org.jetbrains.kotlinx:kotlinx-coroutines-core",version.ref="coroutine"}
coroutine-android = {module ="org.jetbrains.kotlinx:kotlinx-coroutines-android",version.ref ="coroutine"}
coroutine-test = {module ="org.jetbrains.kotlinx:kotlinx-coroutines-test",version.ref ="coroutine-test"}

room-runtime = {module = "androidx.room:room-runtime",version.ref="room"}
room-compiler = {module = "androidx.room:room-compiler",version.ref = "room"}
room-kts = {module ="androidx.room:room-ktx",version.ref="room"}

room-testing = {module = "androidx.room:room-testing",version.ref="room-test"}

test-ext-junit = {module ="androidx.test.ext:junit",version.ref="ext-junit"}
mockito-core ={module = "org.mockito:mockito-core",version.ref="mockito"}

hilt-android ={module ="com.google.dagger:hilt-android",version.ref="hilt"}
hilt-compiler = {module ="com.google.dagger:hilt-android-compiler",version.ref="hilt"}

[bundles]
ui = ["kotlin-stdlib","core-ktx","appcompat","material","constraintlayout"]
navigation = ["navigation-fragment","navigation-ui"]
lifecycle = ["lifecycle-viewmodel","lifecycle-runtime"]
coroutine = ["coroutine-core","coroutine-android"]
room = ["room-runtime","room-kts"]
